## Function for caching the inverse of a matrix 

## The functions below aim to reduce computation time when calculating the inverse of a matrix.
## Instead of computing the inverse of matrix in an iterative way, 
## the function makeCacheMatrix caches the inverse of a matrix by creating a special object.
## This special object stores the matrix and caches the inverse of the matrix.
## The function cachesolve then computes the matrix invers by retrieving it from the cache

## The function makeCacheMatrix generates a special matrix object that can cache its inverse

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y) {
                x <<- y
                inv <<- NULL
        }
        get <- function() x
        setInverse <- function(inverse) inv <<- inverse
        getInverse <- function() inv
        list(set = set,
             get = get,
             setInverse = setInverse,
             getInverse = getInverse)
}


## The function cacheSolve computes the inverse of the special matrix 
## generated by the function makeCacheMatrix. 
## If the inverse has already been calculated and the matrix has not changed, 
## this function retrieves the inverse from the cache

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$getInverse()
        if (!is.null(inv)) {
                message("getting cached data")
                return(inv)
        }
        mat <- x$get()
        inv <- solve(mat, ...)
        x$setInverse(inv)
        inv
}
